name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cbor_enabled: [true, false]
        service_port: [4567, 4568]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Validate build
      run: sbt validate
      env:
        CBOR_ENABLED: ${{ matrix.cbor_enabled }}
        SERVICE_PORT: ${{ matrix.service_port }}
        MUNIT_FLAKY_OK: true
        KINESIS_MOCK_DOCKERFILE: Dockerfile.Simple
    - name: Print Docker Container Listing
      if: ${{ failure() }}
      run: sbt dockerComposePs
    - name: Print Docker Logs
      if: ${{ failure() }}
      run: sbt dockerComposeLogs
    - name: Upload coverage
      uses: codecov/codecov-action@v1